[package]
name = "glimpse"
version = "0.1.0"
edition = "2024"
description = "Framework zero-copy parsing nhị phân, tuân thủ quy tắc đặt tên đơn từ, hiệu suất tối đa. Xem architecture.csv, memories.csv, todo.csv để biết chi tiết thiết kế."


[dependencies] 
